server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_ventas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "*M@815&699s$"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    # Clave secreta (256 bits). Cambiala en produccion.
    secret: Y2FtYmlhbWUtcG9yLXVuYS1jbGF2ZS1tdXktc2VndXJhLXktbGFyZ2EtcGFyYS1qd3QtZW4tcHJvZA==
    # Duracion en milisegundos (24 horas)
    expiration: 86400000

logging:
  level:
    org.springframework.security: INFO
    com.ventas: INFO
